-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 17:42:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_table_evdapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_table_evdapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_table_evdapp` DEFAULT CHARACTER SET utf8 ;
USE `test_table_evdapp` ;

-- -----------------------------------------------------
-- Table `test_table_evdapp`.`reg_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_table_evdapp`.`reg_users` (
  `voterId` INT(12) NOT NULL,
  `voterName` VARCHAR(100) NOT NULL,
  `voterAadhar` INT(12) NOT NULL,
  PRIMARY KEY (`voterId`),
  UNIQUE INDEX `voterAadhar_UNIQUE` (`voterAadhar` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
